#!/bin/bash
export GREEN='\033[0;32m'
NC='\e[0m'
Repo="https://raw.githubusercontent.com/Kulanbagong1/ckck/main/"
# // config Data
echo -e "${GREEN}Config Data${NC}"
wget -q -O /usr/bin/menuv "${Repo}Menu%20Final/menuv.sh && chmod +x /usr/bin/menuv && bash /usr/bin/menuv"
wget -q -O /usr/bin/addv "${Repo}Menu%20Final/addv.sh && chmod +x /usr/bin/addb && bash /usr/bin/addv"
wget -q -O /usr/bin/cekv "${Repo}Menu%20Final/cekv.sh && chmod +x /usr/bin/cekv && bash /usr/bin/cekv"
wget -q -O /usr/bin/delv "${Repo}Menu%20Final/delv.sh && chmod +x /usr/bin/delv && bash /usr/bin/delv"
wget -q -O /usr/bin/renev "${Repo}Menu%20Final/renev.sh && chmod +x /usr/bin/renev && bash /usr/bin/renev"
wget -q -O /usr/bin/menul "${Repo}Menu%20Final/menul.sh && chmod +x /usr/bin/menul && bash /usr/bin/menul"
wget -q -O /usr/bin/addl "${Repo}Menu%20Final/addl.sh && chmod +x /usr/bin/addl && bash /usr/bin/addl"
wget -q -O /usr/bin/cekl "${Repo}Menu%20Final/cekl.sh && chmod +x /usr/bin/cekl && bash /usr/bin/cekl"
wget -q -O /usr/bin/dell "${Repo}Menu%20Final/dell.sh && chmod +x /usr/bin/dell && bash /usr/bin/dell"
wget -q -O /usr/bin/renel "${Repo}Menu%20Final/renel.sh && chmod +x /usr/bin/renel && bash /usr/bin/renel"
wget -q -O /usr/bin/xp "${Repo}xp.sh && chmod +x /usr/bin/xp && bash /usr/bin/xp"
wget -q -O /usr/bin/clog "${Repo}Menu%20Final/clog.sh && chmod +x /usr/bin/cloh && bash /usr/bin/clog"
wget -q -O /usr/bin/addt "${Repo}Menu%20Final/addt.sh && chmod +x /usr/bin/addt && bash /usr/bin/addt"
wget -q -O /usr/bin/cekt "${Repo}Menu%20Final/cekt.sh && chmod +x /usr/bin/cekt && bash /usr/bin/cekt"
wget -q -O /usr/bin/delt "${Repo}Menu%20Final/delt.sh && chmod +x /usr/bin/delt && bash /usr/bin/delt"
wget -q -O /usr/bin/renet "${Repo}Menu%20Final/renet.sh && chmod +x /usr/bin/renet && bash /usr/bin/renet"
wget -q -O /usr/bin/menut "${Repo}Menu%20Final/menut.sh && chmod +x /usr/bin/menut && bash /usr/bin/menut"
wget -q -O /usr/bin/adds "${Repo}Menu%20Final/adds.sh && chmod +x /usr/bin/adds && bash /usr/bin/adds"
wget -q -O /usr/bin/ceks "${Repo}Menu%20Final/ceks.sh && chmod +x /usr/bin/ceks && bash /usr/bin/ceks"
wget -q -O /usr/bin/dels "${Repo}Menu%20Final/dels.sh && chmod +x /usr/bin/dels && bash /usr/bin/dels"
wget -q -O /usr/bin/renes "${Repo}Menu%20Final/renes.sh && chmod +x /usr/bin/renes && bash /usr/bin/renes"
wget -q -O /usr/bin/menus "${Repo}Menu%20Final/menus.sh && chmod +x /usr/bin/menus && bash /usr/bin/menus"
wget -q -O /usr/bin/menussh "${Repo}Menu%20Final/menussh.sh && chmod +x /usr/bin/menussh && bash /usr/bin/menussh"
wget -q -O /usr/bin/usern "${Repo}Menu%20Final/usern.sh && chmod +x /usr/bin/usern && bash /usr/bin/usern"
wget -q -O /usr/bin/menu "${Repo}Menu%20Final/menu.sh && chmod +x /usr/bin/menu && bash /usr/bin/menu"
wget -q -O /usr/bin/menugo "${Repo}Menu%20Final/menugo.sh && chmod +x /usr/bin/menugo && bash /usr/bin/menugo"
wget -q -O /usr/bin/addtrgo "${Repo}Menu%20Final/addtrgo.sh && chmod +x /usr/bin/addtrgo && bash /usr/bin/addtrgo"
wget -q -O /usr/bin/cektrgo "${Repo}Menu%20Final/cektrgo.sh && chmod +x /usr/bin/cektrgo && bash /usr/bin/cektrgo"
wget -q -O /usr/bin/deltrgo "${Repo}Menu%20Final/deltrgo.sh && chmod +x /usr/bin/deltrgo && bash /usr/bin/deltrgo"
wget -q -O /usr/bin/renewtrgo "${Repo}Menu%20Final/renewtrgo.sh && chmod +x /usr/bin/renewtrgo && bash /usr/bin/renewtrgo"
wget -q -O /usr/bin/trialtrojan "${Repo}Menu%20Final/trialtrojan.sh && chmod +x /usr/bin/trialtrojan && bash /usr/bin/trialtrojan"
wget -q -O /usr/bin/trialtrojango "${Repo}Menu%20Final/trialtrojango.sh && chmod +x /usr/bin/trialtrojango && bash /usr/bin/trialtrojango"
wget -q -O /usr/bin/trtl "${Repo}Menu%20Final/trtl.sh && chmod +x /usr/bin/trtl && bash /usr/bin/trtl"
wget -q -O /usr/bin/trtv "${Repo}Menu%20Final/trtv.sh && chmod +x /usr/bin/trtv && bash /usr/bin/trtv"
#lain-lain
wget -q -O /usr/bin/add-host "${Repo}Menu%20Final/Lain/add-host.sh && chmod +x /usr/bin/add-host && bash /usr/bin/add-host"
wget -q -O /usr/bin/domaingratis "${Repo}domaingratis && chmod +x /usr/bin/domaingratis && bash /usr/bin/domaingratis"
wget -q -O /usr/bin/cek-bandwidth "${Repo}Menu%20Final/Lain/cek-bandwidth.sh && chmod +x /usr/bin/cek-bandwidth && bash /usr/bin/cek-bandwidth"
wget -q -O /usr/bin/updatsc "${Repo}update.sh && chmod +x /usr/bin/updatesc && bash /usr/bin/updatesc"
wget -q -O /usr/bin/clearlog "${Repo}Menu%20Final/Lain/clearlog.sh && chmod +x /usr/bin/clearlog && bash /usr/bin/clearlog"
wget -q -O /usr/bin/genssl "${Repo}Menu%20Final/Lain/genssl.sh && chmod +x /usr/bin/genssl && bash /usr/bin/genssl"
wget -q -O /usr/bin/restartsc "${Repo}Menu%20Final/Lain/restart.sh && chmod +x /usr/bin/restartsc && bash /usr/bin/restartsc"
wget -q -O /usr/bin/running "${Repo}Menu%20Final/Lain/running.sh && chmod +x /usr/bin/running && bash /usr/bin/running"
wget -q -O /usr/bin/cek-speed "${Repo}Menu%20Final/Lain/speedtes_cli.py && chmod +x /usr/bin/cek-speed && bash /usr/bin/cek-speed"
wget -q -O /usr/bin/cek-trafik "${Repo}Menu%20Final/Lain/cek-trafik.sh && chmod +x /usr/bin/cek-trafik && bash /usr/bin/cek-trafik"


echo "INSTALL SELESAI"
sleep 2
cd
